# Generated by Django 3.1.7 on 2021-07-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_auto_20210720_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hsc_leaving_certificate',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='hsc_marksheet',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='hsc_passing_certificate',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='hsc_percentage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
