# Generated by Django 3.1.7 on 2021-07-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0019_auto_20210725_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Application_Status',
            field=models.TextField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
