# Generated by Django 3.1.7 on 2021-07-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_application_status_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application_status',
            old_name='condition',
            new_name='status',
        ),
    ]
