# Generated by Django 3.1.7 on 2021-07-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_application_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student_profile',
            field=models.ImageField(upload_to='images'),
        ),
    ]
