# Generated by Django 3.1.7 on 2021-07-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_auto_20210714_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student_profile',
            field=models.ImageField(default=1, upload_to='images'),
        ),
    ]
