# Generated by Django 3.1.7 on 2021-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_auto_20210714_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ssc_leaving_certificate',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_marksheet',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_passing_certificate',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_profile',
            field=models.ImageField(upload_to='images'),
        ),
    ]
