# Generated by Django 3.1.7 on 2021-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_auto_20210720_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cet_percentile',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cet_scorecard',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='jee_percentile',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='jee_scorecard',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
