# Generated by Django 3.1.7 on 2021-07-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_auto_20210720_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jee_percentile',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
