# Generated by Django 3.1.7 on 2021-07-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_auto_20210725_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(default='', max_length=100),
        ),
    ]
