# Generated by Django 3.1.7 on 2021-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
